version: '3.9'
services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pipocaagil
    volumes:
      - ./.docker-data/postgres:/var/lib/postgresql/data
